:- module(cscope_db, [
    % Persistent predicates (query)
    symbol/4,              % symbol(File, Symbol, Line, Context)
    def/5,                 % def(File, Symbol, Line, Context, Kind)
    calls/5,               % calls(File, Caller, Line, Context, Callee)

    % Assertion predicates (generated by library(persistency))
    assert_symbol/4,       % assert_symbol(File, Symbol, Line, Context)
    assert_def/5,          % assert_def(File, Symbol, Line, Context, Kind)
    assert_calls/5,        % assert_calls(File, Caller, Line, Context, Callee)
    retractall_symbol/4,   % retractall_symbol(File, Symbol, Line, Context)
    retractall_def/5,      % retractall_def(File, Symbol, Line, Context, Kind)
    retractall_calls/5,    % retractall_calls(File, Caller, Line, Context, Callee)

    % Database management
    attach_db/0,           % Attach persistence database
    attach_db/1,           % attach_db(+Options)
    db_statistics/0,       % Print database statistics
    clear_db/0,            % Clear all persistent facts
    compact_journal/0      % Compact journal file to remove bloat
]).

:- use_module(library(persistency)).

%! Persistent predicate declarations
%
% These predicates are automatically persisted to disk using library(persistency).
% The persistence file is: knowledge/cscope_facts.db

:- persistent
    symbol(file:atom, symbol:atom, line:integer, context:string),
    def(file:atom, symbol:atom, line:integer, context:string, kind:atom),
    calls(file:atom, caller:atom, line:integer, context:string, callee:atom).

%! attach_db is det.
%! attach_db(+Options:list) is det.
%
% Attach the persistent database from knowledge/cscope_facts.db
% This is called automatically when the module loads.
%
% Options:
%   - silent(true/false): Suppress informational messages (default: false)
%   - check_size(true/false): Check file size before loading (default: true)
%   - max_mb(N): Maximum file size in MB to load without warning (default: 50)
%
% Journal files can become large over time due to repeated assert/retract operations.
% Use compact_journal/0 periodically to rebuild the journal and reduce size.
%
% @see compact_journal/0

attach_db :- attach_db([]).

attach_db(Options) :-
    % Set up options with defaults
    (memberchk(silent(Silent), Options) -> true ; Silent = false),
    (memberchk(check_size(CheckSize), Options) -> true ; CheckSize = true),
    (memberchk(max_mb(MaxMB), Options) -> true ; MaxMB = 50),

    % Ensure knowledge directory exists
    Directory = 'knowledge',
    (exists_directory(Directory) -> true ; make_directory(Directory)),

    % Database file path
    DbFile = 'knowledge/cscope_facts.db',

    % Check file size if requested
    (CheckSize, exists_file(DbFile) ->
        size_file(DbFile, Bytes),
        SizeMB is Bytes / (1024 * 1024),
        (SizeMB > MaxMB ->
            format('~n*** WARNING: Database file is ~1f MB ***~n', [SizeMB]),
            format('Loading may take several minutes. Consider running compact_journal/0.~n~n', [])
        ; Silent = false ->
            format('Loading database (~1f MB)...~n', [SizeMB])
        ; true)
    ; true),

    % Attach the database
    db_attach(DbFile, [sync(close)]),

    % Report statistics if not silent
    (Silent = false ->
        (exists_file(DbFile) ->
            db_statistics
        ; format('Created new database: ~w~n', [DbFile]))
    ; true).

%! db_statistics is det.
%
% Print statistics about the persistent database.

db_statistics :-
    aggregate_all(count, symbol(_, _, _, _), SymbolCount),
    aggregate_all(count, def(_, _, _, _, _), DefCount),
    aggregate_all(count, calls(_, _, _, _, _), CallCount),
    format('Database statistics:~n', []),
    format('  Symbols:     ~D~n', [SymbolCount]),
    format('  Definitions: ~D~n', [DefCount]),
    format('  Calls:       ~D~n', [CallCount]).

%! clear_db is det.
%
% Clear all persistent facts from the database.
% This is useful for starting fresh with new data.
%
% WARNING: This operation cannot be undone!

clear_db :-
    format('Clearing all persistent facts...~n', []),
    retractall_symbol(_, _, _, _),
    retractall_def(_, _, _, _, _),
    retractall_calls(_, _, _, _, _),
    format('Database cleared.~n', []).

%! compact_journal is det.
%
% Compact the journal file by rebuilding it from current facts.
%
% The persistence file is a journal of assert/retract operations.
% Over time, with repeated imports and retracts, the journal can become
% bloated with redundant operations, causing slow load times.
%
% This predicate rebuilds the journal to contain only the current facts,
% removing all historical assert/retract operations.
%
% Example usage:
%   ?- compact_journal.
%   Compacting journal (this may take a moment)...
%   Journal compacted successfully.

compact_journal :-
    format('Compacting journal (this may take a moment)...~n', []),

    % Collect all current facts
    findall(symbol(F,S,L,C), symbol(F,S,L,C), Symbols),
    findall(def(F,S,L,C,K), def(F,S,L,C,K), Defs),
    findall(calls(F,Cr,L,C,Ce), calls(F,Cr,L,C,Ce), Calls),

    % Detach database
    db_detach,

    % Delete old journal file
    DbFile = 'knowledge/cscope_facts.db',
    (exists_file(DbFile) -> delete_file(DbFile) ; true),

    % Reattach (creates new empty journal)
    db_attach(DbFile, [sync(close)]),

    % Re-assert all facts
    forall(member(symbol(F,S,L,C), Symbols), assert_symbol(F,S,L,C)),
    forall(member(def(F,S,L,C,K), Defs), assert_def(F,S,L,C,K)),
    forall(member(calls(F,Cr,L,C,Ce), Calls), assert_calls(F,Cr,L,C,Ce)),

    format('Journal compacted successfully.~n', []).

%! Module initialization
%
% Automatically attach the database when this module is loaded.

:- initialization(attach_db([silent(false)])).
